// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: vecdb.proto
#ifndef GRPC_vecdb_2eproto__INCLUDED
#define GRPC_vecdb_2eproto__INCLUDED

#include "vecdb.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>

namespace vecdb {

// ──────────────────────────────────────────────────────────────────────────────
//  vecdb gRPC Service — Phase 6
//
//  All vectors are transmitted as raw IEEE-754 float32 bytes, little-endian.
//  Encoding: `bytes vector = N` — client packs dim floats, server unpacks them.
//
//  Authentication: every RPC requires a bearer token in the gRPC metadata:
//    key:   "authorization"
//    value: "Bearer <token>"
// ──────────────────────────────────────────────────────────────────────────────
//
class VectorDB final {
 public:
  static constexpr char const* service_full_name() {
    return "vecdb.VectorDB";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    // Insert a single vector
    virtual ::grpc::Status Insert(::grpc::ClientContext* context, const ::vecdb::InsertRequest& request, ::vecdb::InsertResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::vecdb::InsertResponse>> AsyncInsert(::grpc::ClientContext* context, const ::vecdb::InsertRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::vecdb::InsertResponse>>(AsyncInsertRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::vecdb::InsertResponse>> PrepareAsyncInsert(::grpc::ClientContext* context, const ::vecdb::InsertRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::vecdb::InsertResponse>>(PrepareAsyncInsertRaw(context, request, cq));
    }
    // Bulk insert (client streaming)
    std::unique_ptr< ::grpc::ClientWriterInterface< ::vecdb::InsertRequest>> BulkInsert(::grpc::ClientContext* context, ::vecdb::BulkInsertResponse* response) {
      return std::unique_ptr< ::grpc::ClientWriterInterface< ::vecdb::InsertRequest>>(BulkInsertRaw(context, response));
    }
    std::unique_ptr< ::grpc::ClientAsyncWriterInterface< ::vecdb::InsertRequest>> AsyncBulkInsert(::grpc::ClientContext* context, ::vecdb::BulkInsertResponse* response, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncWriterInterface< ::vecdb::InsertRequest>>(AsyncBulkInsertRaw(context, response, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncWriterInterface< ::vecdb::InsertRequest>> PrepareAsyncBulkInsert(::grpc::ClientContext* context, ::vecdb::BulkInsertResponse* response, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncWriterInterface< ::vecdb::InsertRequest>>(PrepareAsyncBulkInsertRaw(context, response, cq));
    }
    // Search for nearest neighbours
    virtual ::grpc::Status Search(::grpc::ClientContext* context, const ::vecdb::SearchRequest& request, ::vecdb::SearchResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::vecdb::SearchResponse>> AsyncSearch(::grpc::ClientContext* context, const ::vecdb::SearchRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::vecdb::SearchResponse>>(AsyncSearchRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::vecdb::SearchResponse>> PrepareAsyncSearch(::grpc::ClientContext* context, const ::vecdb::SearchRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::vecdb::SearchResponse>>(PrepareAsyncSearchRaw(context, request, cq));
    }
    // Delete a vector by id
    virtual ::grpc::Status Delete(::grpc::ClientContext* context, const ::vecdb::DeleteRequest& request, ::vecdb::DeleteResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::vecdb::DeleteResponse>> AsyncDelete(::grpc::ClientContext* context, const ::vecdb::DeleteRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::vecdb::DeleteResponse>>(AsyncDeleteRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::vecdb::DeleteResponse>> PrepareAsyncDelete(::grpc::ClientContext* context, const ::vecdb::DeleteRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::vecdb::DeleteResponse>>(PrepareAsyncDeleteRaw(context, request, cq));
    }
    // Get collection / shard info
    virtual ::grpc::Status GetInfo(::grpc::ClientContext* context, const ::vecdb::InfoRequest& request, ::vecdb::InfoResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::vecdb::InfoResponse>> AsyncGetInfo(::grpc::ClientContext* context, const ::vecdb::InfoRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::vecdb::InfoResponse>>(AsyncGetInfoRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::vecdb::InfoResponse>> PrepareAsyncGetInfo(::grpc::ClientContext* context, const ::vecdb::InfoRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::vecdb::InfoResponse>>(PrepareAsyncGetInfoRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      // Insert a single vector
      virtual void Insert(::grpc::ClientContext* context, const ::vecdb::InsertRequest* request, ::vecdb::InsertResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void Insert(::grpc::ClientContext* context, const ::vecdb::InsertRequest* request, ::vecdb::InsertResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      // Bulk insert (client streaming)
      virtual void BulkInsert(::grpc::ClientContext* context, ::vecdb::BulkInsertResponse* response, ::grpc::ClientWriteReactor< ::vecdb::InsertRequest>* reactor) = 0;
      // Search for nearest neighbours
      virtual void Search(::grpc::ClientContext* context, const ::vecdb::SearchRequest* request, ::vecdb::SearchResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void Search(::grpc::ClientContext* context, const ::vecdb::SearchRequest* request, ::vecdb::SearchResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      // Delete a vector by id
      virtual void Delete(::grpc::ClientContext* context, const ::vecdb::DeleteRequest* request, ::vecdb::DeleteResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void Delete(::grpc::ClientContext* context, const ::vecdb::DeleteRequest* request, ::vecdb::DeleteResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      // Get collection / shard info
      virtual void GetInfo(::grpc::ClientContext* context, const ::vecdb::InfoRequest* request, ::vecdb::InfoResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void GetInfo(::grpc::ClientContext* context, const ::vecdb::InfoRequest* request, ::vecdb::InfoResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::vecdb::InsertResponse>* AsyncInsertRaw(::grpc::ClientContext* context, const ::vecdb::InsertRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::vecdb::InsertResponse>* PrepareAsyncInsertRaw(::grpc::ClientContext* context, const ::vecdb::InsertRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientWriterInterface< ::vecdb::InsertRequest>* BulkInsertRaw(::grpc::ClientContext* context, ::vecdb::BulkInsertResponse* response) = 0;
    virtual ::grpc::ClientAsyncWriterInterface< ::vecdb::InsertRequest>* AsyncBulkInsertRaw(::grpc::ClientContext* context, ::vecdb::BulkInsertResponse* response, ::grpc::CompletionQueue* cq, void* tag) = 0;
    virtual ::grpc::ClientAsyncWriterInterface< ::vecdb::InsertRequest>* PrepareAsyncBulkInsertRaw(::grpc::ClientContext* context, ::vecdb::BulkInsertResponse* response, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::vecdb::SearchResponse>* AsyncSearchRaw(::grpc::ClientContext* context, const ::vecdb::SearchRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::vecdb::SearchResponse>* PrepareAsyncSearchRaw(::grpc::ClientContext* context, const ::vecdb::SearchRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::vecdb::DeleteResponse>* AsyncDeleteRaw(::grpc::ClientContext* context, const ::vecdb::DeleteRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::vecdb::DeleteResponse>* PrepareAsyncDeleteRaw(::grpc::ClientContext* context, const ::vecdb::DeleteRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::vecdb::InfoResponse>* AsyncGetInfoRaw(::grpc::ClientContext* context, const ::vecdb::InfoRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::vecdb::InfoResponse>* PrepareAsyncGetInfoRaw(::grpc::ClientContext* context, const ::vecdb::InfoRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status Insert(::grpc::ClientContext* context, const ::vecdb::InsertRequest& request, ::vecdb::InsertResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::vecdb::InsertResponse>> AsyncInsert(::grpc::ClientContext* context, const ::vecdb::InsertRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::vecdb::InsertResponse>>(AsyncInsertRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::vecdb::InsertResponse>> PrepareAsyncInsert(::grpc::ClientContext* context, const ::vecdb::InsertRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::vecdb::InsertResponse>>(PrepareAsyncInsertRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientWriter< ::vecdb::InsertRequest>> BulkInsert(::grpc::ClientContext* context, ::vecdb::BulkInsertResponse* response) {
      return std::unique_ptr< ::grpc::ClientWriter< ::vecdb::InsertRequest>>(BulkInsertRaw(context, response));
    }
    std::unique_ptr< ::grpc::ClientAsyncWriter< ::vecdb::InsertRequest>> AsyncBulkInsert(::grpc::ClientContext* context, ::vecdb::BulkInsertResponse* response, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncWriter< ::vecdb::InsertRequest>>(AsyncBulkInsertRaw(context, response, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncWriter< ::vecdb::InsertRequest>> PrepareAsyncBulkInsert(::grpc::ClientContext* context, ::vecdb::BulkInsertResponse* response, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncWriter< ::vecdb::InsertRequest>>(PrepareAsyncBulkInsertRaw(context, response, cq));
    }
    ::grpc::Status Search(::grpc::ClientContext* context, const ::vecdb::SearchRequest& request, ::vecdb::SearchResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::vecdb::SearchResponse>> AsyncSearch(::grpc::ClientContext* context, const ::vecdb::SearchRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::vecdb::SearchResponse>>(AsyncSearchRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::vecdb::SearchResponse>> PrepareAsyncSearch(::grpc::ClientContext* context, const ::vecdb::SearchRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::vecdb::SearchResponse>>(PrepareAsyncSearchRaw(context, request, cq));
    }
    ::grpc::Status Delete(::grpc::ClientContext* context, const ::vecdb::DeleteRequest& request, ::vecdb::DeleteResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::vecdb::DeleteResponse>> AsyncDelete(::grpc::ClientContext* context, const ::vecdb::DeleteRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::vecdb::DeleteResponse>>(AsyncDeleteRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::vecdb::DeleteResponse>> PrepareAsyncDelete(::grpc::ClientContext* context, const ::vecdb::DeleteRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::vecdb::DeleteResponse>>(PrepareAsyncDeleteRaw(context, request, cq));
    }
    ::grpc::Status GetInfo(::grpc::ClientContext* context, const ::vecdb::InfoRequest& request, ::vecdb::InfoResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::vecdb::InfoResponse>> AsyncGetInfo(::grpc::ClientContext* context, const ::vecdb::InfoRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::vecdb::InfoResponse>>(AsyncGetInfoRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::vecdb::InfoResponse>> PrepareAsyncGetInfo(::grpc::ClientContext* context, const ::vecdb::InfoRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::vecdb::InfoResponse>>(PrepareAsyncGetInfoRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void Insert(::grpc::ClientContext* context, const ::vecdb::InsertRequest* request, ::vecdb::InsertResponse* response, std::function<void(::grpc::Status)>) override;
      void Insert(::grpc::ClientContext* context, const ::vecdb::InsertRequest* request, ::vecdb::InsertResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      void BulkInsert(::grpc::ClientContext* context, ::vecdb::BulkInsertResponse* response, ::grpc::ClientWriteReactor< ::vecdb::InsertRequest>* reactor) override;
      void Search(::grpc::ClientContext* context, const ::vecdb::SearchRequest* request, ::vecdb::SearchResponse* response, std::function<void(::grpc::Status)>) override;
      void Search(::grpc::ClientContext* context, const ::vecdb::SearchRequest* request, ::vecdb::SearchResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      void Delete(::grpc::ClientContext* context, const ::vecdb::DeleteRequest* request, ::vecdb::DeleteResponse* response, std::function<void(::grpc::Status)>) override;
      void Delete(::grpc::ClientContext* context, const ::vecdb::DeleteRequest* request, ::vecdb::DeleteResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      void GetInfo(::grpc::ClientContext* context, const ::vecdb::InfoRequest* request, ::vecdb::InfoResponse* response, std::function<void(::grpc::Status)>) override;
      void GetInfo(::grpc::ClientContext* context, const ::vecdb::InfoRequest* request, ::vecdb::InfoResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::vecdb::InsertResponse>* AsyncInsertRaw(::grpc::ClientContext* context, const ::vecdb::InsertRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::vecdb::InsertResponse>* PrepareAsyncInsertRaw(::grpc::ClientContext* context, const ::vecdb::InsertRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientWriter< ::vecdb::InsertRequest>* BulkInsertRaw(::grpc::ClientContext* context, ::vecdb::BulkInsertResponse* response) override;
    ::grpc::ClientAsyncWriter< ::vecdb::InsertRequest>* AsyncBulkInsertRaw(::grpc::ClientContext* context, ::vecdb::BulkInsertResponse* response, ::grpc::CompletionQueue* cq, void* tag) override;
    ::grpc::ClientAsyncWriter< ::vecdb::InsertRequest>* PrepareAsyncBulkInsertRaw(::grpc::ClientContext* context, ::vecdb::BulkInsertResponse* response, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::vecdb::SearchResponse>* AsyncSearchRaw(::grpc::ClientContext* context, const ::vecdb::SearchRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::vecdb::SearchResponse>* PrepareAsyncSearchRaw(::grpc::ClientContext* context, const ::vecdb::SearchRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::vecdb::DeleteResponse>* AsyncDeleteRaw(::grpc::ClientContext* context, const ::vecdb::DeleteRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::vecdb::DeleteResponse>* PrepareAsyncDeleteRaw(::grpc::ClientContext* context, const ::vecdb::DeleteRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::vecdb::InfoResponse>* AsyncGetInfoRaw(::grpc::ClientContext* context, const ::vecdb::InfoRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::vecdb::InfoResponse>* PrepareAsyncGetInfoRaw(::grpc::ClientContext* context, const ::vecdb::InfoRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_Insert_;
    const ::grpc::internal::RpcMethod rpcmethod_BulkInsert_;
    const ::grpc::internal::RpcMethod rpcmethod_Search_;
    const ::grpc::internal::RpcMethod rpcmethod_Delete_;
    const ::grpc::internal::RpcMethod rpcmethod_GetInfo_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    // Insert a single vector
    virtual ::grpc::Status Insert(::grpc::ServerContext* context, const ::vecdb::InsertRequest* request, ::vecdb::InsertResponse* response);
    // Bulk insert (client streaming)
    virtual ::grpc::Status BulkInsert(::grpc::ServerContext* context, ::grpc::ServerReader< ::vecdb::InsertRequest>* reader, ::vecdb::BulkInsertResponse* response);
    // Search for nearest neighbours
    virtual ::grpc::Status Search(::grpc::ServerContext* context, const ::vecdb::SearchRequest* request, ::vecdb::SearchResponse* response);
    // Delete a vector by id
    virtual ::grpc::Status Delete(::grpc::ServerContext* context, const ::vecdb::DeleteRequest* request, ::vecdb::DeleteResponse* response);
    // Get collection / shard info
    virtual ::grpc::Status GetInfo(::grpc::ServerContext* context, const ::vecdb::InfoRequest* request, ::vecdb::InfoResponse* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_Insert : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_Insert() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_Insert() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Insert(::grpc::ServerContext* /*context*/, const ::vecdb::InsertRequest* /*request*/, ::vecdb::InsertResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestInsert(::grpc::ServerContext* context, ::vecdb::InsertRequest* request, ::grpc::ServerAsyncResponseWriter< ::vecdb::InsertResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_BulkInsert : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_BulkInsert() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_BulkInsert() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status BulkInsert(::grpc::ServerContext* /*context*/, ::grpc::ServerReader< ::vecdb::InsertRequest>* /*reader*/, ::vecdb::BulkInsertResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestBulkInsert(::grpc::ServerContext* context, ::grpc::ServerAsyncReader< ::vecdb::BulkInsertResponse, ::vecdb::InsertRequest>* reader, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncClientStreaming(1, context, reader, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_Search : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_Search() {
      ::grpc::Service::MarkMethodAsync(2);
    }
    ~WithAsyncMethod_Search() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Search(::grpc::ServerContext* /*context*/, const ::vecdb::SearchRequest* /*request*/, ::vecdb::SearchResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestSearch(::grpc::ServerContext* context, ::vecdb::SearchRequest* request, ::grpc::ServerAsyncResponseWriter< ::vecdb::SearchResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(2, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_Delete : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_Delete() {
      ::grpc::Service::MarkMethodAsync(3);
    }
    ~WithAsyncMethod_Delete() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Delete(::grpc::ServerContext* /*context*/, const ::vecdb::DeleteRequest* /*request*/, ::vecdb::DeleteResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestDelete(::grpc::ServerContext* context, ::vecdb::DeleteRequest* request, ::grpc::ServerAsyncResponseWriter< ::vecdb::DeleteResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(3, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_GetInfo : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_GetInfo() {
      ::grpc::Service::MarkMethodAsync(4);
    }
    ~WithAsyncMethod_GetInfo() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetInfo(::grpc::ServerContext* /*context*/, const ::vecdb::InfoRequest* /*request*/, ::vecdb::InfoResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetInfo(::grpc::ServerContext* context, ::vecdb::InfoRequest* request, ::grpc::ServerAsyncResponseWriter< ::vecdb::InfoResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(4, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_Insert<WithAsyncMethod_BulkInsert<WithAsyncMethod_Search<WithAsyncMethod_Delete<WithAsyncMethod_GetInfo<Service > > > > > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_Insert : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_Insert() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::vecdb::InsertRequest, ::vecdb::InsertResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::vecdb::InsertRequest* request, ::vecdb::InsertResponse* response) { return this->Insert(context, request, response); }));}
    void SetMessageAllocatorFor_Insert(
        ::grpc::MessageAllocator< ::vecdb::InsertRequest, ::vecdb::InsertResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::vecdb::InsertRequest, ::vecdb::InsertResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_Insert() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Insert(::grpc::ServerContext* /*context*/, const ::vecdb::InsertRequest* /*request*/, ::vecdb::InsertResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* Insert(
      ::grpc::CallbackServerContext* /*context*/, const ::vecdb::InsertRequest* /*request*/, ::vecdb::InsertResponse* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_BulkInsert : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_BulkInsert() {
      ::grpc::Service::MarkMethodCallback(1,
          new ::grpc::internal::CallbackClientStreamingHandler< ::vecdb::InsertRequest, ::vecdb::BulkInsertResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, ::vecdb::BulkInsertResponse* response) { return this->BulkInsert(context, response); }));
    }
    ~WithCallbackMethod_BulkInsert() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status BulkInsert(::grpc::ServerContext* /*context*/, ::grpc::ServerReader< ::vecdb::InsertRequest>* /*reader*/, ::vecdb::BulkInsertResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerReadReactor< ::vecdb::InsertRequest>* BulkInsert(
      ::grpc::CallbackServerContext* /*context*/, ::vecdb::BulkInsertResponse* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_Search : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_Search() {
      ::grpc::Service::MarkMethodCallback(2,
          new ::grpc::internal::CallbackUnaryHandler< ::vecdb::SearchRequest, ::vecdb::SearchResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::vecdb::SearchRequest* request, ::vecdb::SearchResponse* response) { return this->Search(context, request, response); }));}
    void SetMessageAllocatorFor_Search(
        ::grpc::MessageAllocator< ::vecdb::SearchRequest, ::vecdb::SearchResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(2);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::vecdb::SearchRequest, ::vecdb::SearchResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_Search() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Search(::grpc::ServerContext* /*context*/, const ::vecdb::SearchRequest* /*request*/, ::vecdb::SearchResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* Search(
      ::grpc::CallbackServerContext* /*context*/, const ::vecdb::SearchRequest* /*request*/, ::vecdb::SearchResponse* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_Delete : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_Delete() {
      ::grpc::Service::MarkMethodCallback(3,
          new ::grpc::internal::CallbackUnaryHandler< ::vecdb::DeleteRequest, ::vecdb::DeleteResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::vecdb::DeleteRequest* request, ::vecdb::DeleteResponse* response) { return this->Delete(context, request, response); }));}
    void SetMessageAllocatorFor_Delete(
        ::grpc::MessageAllocator< ::vecdb::DeleteRequest, ::vecdb::DeleteResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(3);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::vecdb::DeleteRequest, ::vecdb::DeleteResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_Delete() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Delete(::grpc::ServerContext* /*context*/, const ::vecdb::DeleteRequest* /*request*/, ::vecdb::DeleteResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* Delete(
      ::grpc::CallbackServerContext* /*context*/, const ::vecdb::DeleteRequest* /*request*/, ::vecdb::DeleteResponse* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_GetInfo : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_GetInfo() {
      ::grpc::Service::MarkMethodCallback(4,
          new ::grpc::internal::CallbackUnaryHandler< ::vecdb::InfoRequest, ::vecdb::InfoResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::vecdb::InfoRequest* request, ::vecdb::InfoResponse* response) { return this->GetInfo(context, request, response); }));}
    void SetMessageAllocatorFor_GetInfo(
        ::grpc::MessageAllocator< ::vecdb::InfoRequest, ::vecdb::InfoResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(4);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::vecdb::InfoRequest, ::vecdb::InfoResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_GetInfo() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetInfo(::grpc::ServerContext* /*context*/, const ::vecdb::InfoRequest* /*request*/, ::vecdb::InfoResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetInfo(
      ::grpc::CallbackServerContext* /*context*/, const ::vecdb::InfoRequest* /*request*/, ::vecdb::InfoResponse* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_Insert<WithCallbackMethod_BulkInsert<WithCallbackMethod_Search<WithCallbackMethod_Delete<WithCallbackMethod_GetInfo<Service > > > > > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_Insert : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_Insert() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_Insert() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Insert(::grpc::ServerContext* /*context*/, const ::vecdb::InsertRequest* /*request*/, ::vecdb::InsertResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_BulkInsert : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_BulkInsert() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_BulkInsert() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status BulkInsert(::grpc::ServerContext* /*context*/, ::grpc::ServerReader< ::vecdb::InsertRequest>* /*reader*/, ::vecdb::BulkInsertResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_Search : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_Search() {
      ::grpc::Service::MarkMethodGeneric(2);
    }
    ~WithGenericMethod_Search() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Search(::grpc::ServerContext* /*context*/, const ::vecdb::SearchRequest* /*request*/, ::vecdb::SearchResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_Delete : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_Delete() {
      ::grpc::Service::MarkMethodGeneric(3);
    }
    ~WithGenericMethod_Delete() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Delete(::grpc::ServerContext* /*context*/, const ::vecdb::DeleteRequest* /*request*/, ::vecdb::DeleteResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_GetInfo : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_GetInfo() {
      ::grpc::Service::MarkMethodGeneric(4);
    }
    ~WithGenericMethod_GetInfo() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetInfo(::grpc::ServerContext* /*context*/, const ::vecdb::InfoRequest* /*request*/, ::vecdb::InfoResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_Insert : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_Insert() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_Insert() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Insert(::grpc::ServerContext* /*context*/, const ::vecdb::InsertRequest* /*request*/, ::vecdb::InsertResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestInsert(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_BulkInsert : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_BulkInsert() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_BulkInsert() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status BulkInsert(::grpc::ServerContext* /*context*/, ::grpc::ServerReader< ::vecdb::InsertRequest>* /*reader*/, ::vecdb::BulkInsertResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestBulkInsert(::grpc::ServerContext* context, ::grpc::ServerAsyncReader< ::grpc::ByteBuffer, ::grpc::ByteBuffer>* reader, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncClientStreaming(1, context, reader, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_Search : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_Search() {
      ::grpc::Service::MarkMethodRaw(2);
    }
    ~WithRawMethod_Search() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Search(::grpc::ServerContext* /*context*/, const ::vecdb::SearchRequest* /*request*/, ::vecdb::SearchResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestSearch(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(2, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_Delete : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_Delete() {
      ::grpc::Service::MarkMethodRaw(3);
    }
    ~WithRawMethod_Delete() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Delete(::grpc::ServerContext* /*context*/, const ::vecdb::DeleteRequest* /*request*/, ::vecdb::DeleteResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestDelete(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(3, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_GetInfo : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_GetInfo() {
      ::grpc::Service::MarkMethodRaw(4);
    }
    ~WithRawMethod_GetInfo() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetInfo(::grpc::ServerContext* /*context*/, const ::vecdb::InfoRequest* /*request*/, ::vecdb::InfoResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetInfo(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(4, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_Insert : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_Insert() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->Insert(context, request, response); }));
    }
    ~WithRawCallbackMethod_Insert() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Insert(::grpc::ServerContext* /*context*/, const ::vecdb::InsertRequest* /*request*/, ::vecdb::InsertResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* Insert(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_BulkInsert : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_BulkInsert() {
      ::grpc::Service::MarkMethodRawCallback(1,
          new ::grpc::internal::CallbackClientStreamingHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, ::grpc::ByteBuffer* response) { return this->BulkInsert(context, response); }));
    }
    ~WithRawCallbackMethod_BulkInsert() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status BulkInsert(::grpc::ServerContext* /*context*/, ::grpc::ServerReader< ::vecdb::InsertRequest>* /*reader*/, ::vecdb::BulkInsertResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerReadReactor< ::grpc::ByteBuffer>* BulkInsert(
      ::grpc::CallbackServerContext* /*context*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_Search : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_Search() {
      ::grpc::Service::MarkMethodRawCallback(2,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->Search(context, request, response); }));
    }
    ~WithRawCallbackMethod_Search() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Search(::grpc::ServerContext* /*context*/, const ::vecdb::SearchRequest* /*request*/, ::vecdb::SearchResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* Search(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_Delete : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_Delete() {
      ::grpc::Service::MarkMethodRawCallback(3,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->Delete(context, request, response); }));
    }
    ~WithRawCallbackMethod_Delete() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Delete(::grpc::ServerContext* /*context*/, const ::vecdb::DeleteRequest* /*request*/, ::vecdb::DeleteResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* Delete(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_GetInfo : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_GetInfo() {
      ::grpc::Service::MarkMethodRawCallback(4,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->GetInfo(context, request, response); }));
    }
    ~WithRawCallbackMethod_GetInfo() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetInfo(::grpc::ServerContext* /*context*/, const ::vecdb::InfoRequest* /*request*/, ::vecdb::InfoResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetInfo(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_Insert : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_Insert() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::vecdb::InsertRequest, ::vecdb::InsertResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::vecdb::InsertRequest, ::vecdb::InsertResponse>* streamer) {
                       return this->StreamedInsert(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_Insert() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status Insert(::grpc::ServerContext* /*context*/, const ::vecdb::InsertRequest* /*request*/, ::vecdb::InsertResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedInsert(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::vecdb::InsertRequest,::vecdb::InsertResponse>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_Search : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_Search() {
      ::grpc::Service::MarkMethodStreamed(2,
        new ::grpc::internal::StreamedUnaryHandler<
          ::vecdb::SearchRequest, ::vecdb::SearchResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::vecdb::SearchRequest, ::vecdb::SearchResponse>* streamer) {
                       return this->StreamedSearch(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_Search() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status Search(::grpc::ServerContext* /*context*/, const ::vecdb::SearchRequest* /*request*/, ::vecdb::SearchResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedSearch(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::vecdb::SearchRequest,::vecdb::SearchResponse>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_Delete : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_Delete() {
      ::grpc::Service::MarkMethodStreamed(3,
        new ::grpc::internal::StreamedUnaryHandler<
          ::vecdb::DeleteRequest, ::vecdb::DeleteResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::vecdb::DeleteRequest, ::vecdb::DeleteResponse>* streamer) {
                       return this->StreamedDelete(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_Delete() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status Delete(::grpc::ServerContext* /*context*/, const ::vecdb::DeleteRequest* /*request*/, ::vecdb::DeleteResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedDelete(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::vecdb::DeleteRequest,::vecdb::DeleteResponse>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_GetInfo : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_GetInfo() {
      ::grpc::Service::MarkMethodStreamed(4,
        new ::grpc::internal::StreamedUnaryHandler<
          ::vecdb::InfoRequest, ::vecdb::InfoResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::vecdb::InfoRequest, ::vecdb::InfoResponse>* streamer) {
                       return this->StreamedGetInfo(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_GetInfo() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status GetInfo(::grpc::ServerContext* /*context*/, const ::vecdb::InfoRequest* /*request*/, ::vecdb::InfoResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedGetInfo(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::vecdb::InfoRequest,::vecdb::InfoResponse>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_Insert<WithStreamedUnaryMethod_Search<WithStreamedUnaryMethod_Delete<WithStreamedUnaryMethod_GetInfo<Service > > > > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_Insert<WithStreamedUnaryMethod_Search<WithStreamedUnaryMethod_Delete<WithStreamedUnaryMethod_GetInfo<Service > > > > StreamedService;
};

}  // namespace vecdb


#endif  // GRPC_vecdb_2eproto__INCLUDED
