// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: vecdb.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_vecdb_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_vecdb_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_bases.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_vecdb_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_vecdb_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_vecdb_2eproto;
namespace vecdb {
class BulkInsertResponse;
struct BulkInsertResponseDefaultTypeInternal;
extern BulkInsertResponseDefaultTypeInternal _BulkInsertResponse_default_instance_;
class DeleteRequest;
struct DeleteRequestDefaultTypeInternal;
extern DeleteRequestDefaultTypeInternal _DeleteRequest_default_instance_;
class DeleteResponse;
struct DeleteResponseDefaultTypeInternal;
extern DeleteResponseDefaultTypeInternal _DeleteResponse_default_instance_;
class InfoRequest;
struct InfoRequestDefaultTypeInternal;
extern InfoRequestDefaultTypeInternal _InfoRequest_default_instance_;
class InfoResponse;
struct InfoResponseDefaultTypeInternal;
extern InfoResponseDefaultTypeInternal _InfoResponse_default_instance_;
class InsertRequest;
struct InsertRequestDefaultTypeInternal;
extern InsertRequestDefaultTypeInternal _InsertRequest_default_instance_;
class InsertResponse;
struct InsertResponseDefaultTypeInternal;
extern InsertResponseDefaultTypeInternal _InsertResponse_default_instance_;
class SearchRequest;
struct SearchRequestDefaultTypeInternal;
extern SearchRequestDefaultTypeInternal _SearchRequest_default_instance_;
class SearchResponse;
struct SearchResponseDefaultTypeInternal;
extern SearchResponseDefaultTypeInternal _SearchResponse_default_instance_;
class SearchResult;
struct SearchResultDefaultTypeInternal;
extern SearchResultDefaultTypeInternal _SearchResult_default_instance_;
class ShardInfo;
struct ShardInfoDefaultTypeInternal;
extern ShardInfoDefaultTypeInternal _ShardInfo_default_instance_;
}  // namespace vecdb
PROTOBUF_NAMESPACE_OPEN
template<> ::vecdb::BulkInsertResponse* Arena::CreateMaybeMessage<::vecdb::BulkInsertResponse>(Arena*);
template<> ::vecdb::DeleteRequest* Arena::CreateMaybeMessage<::vecdb::DeleteRequest>(Arena*);
template<> ::vecdb::DeleteResponse* Arena::CreateMaybeMessage<::vecdb::DeleteResponse>(Arena*);
template<> ::vecdb::InfoRequest* Arena::CreateMaybeMessage<::vecdb::InfoRequest>(Arena*);
template<> ::vecdb::InfoResponse* Arena::CreateMaybeMessage<::vecdb::InfoResponse>(Arena*);
template<> ::vecdb::InsertRequest* Arena::CreateMaybeMessage<::vecdb::InsertRequest>(Arena*);
template<> ::vecdb::InsertResponse* Arena::CreateMaybeMessage<::vecdb::InsertResponse>(Arena*);
template<> ::vecdb::SearchRequest* Arena::CreateMaybeMessage<::vecdb::SearchRequest>(Arena*);
template<> ::vecdb::SearchResponse* Arena::CreateMaybeMessage<::vecdb::SearchResponse>(Arena*);
template<> ::vecdb::SearchResult* Arena::CreateMaybeMessage<::vecdb::SearchResult>(Arena*);
template<> ::vecdb::ShardInfo* Arena::CreateMaybeMessage<::vecdb::ShardInfo>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace vecdb {

// ===================================================================

class InsertRequest final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:vecdb.InsertRequest) */ {
 public:
  inline InsertRequest() : InsertRequest(nullptr) {}
  ~InsertRequest() override;
  explicit PROTOBUF_CONSTEXPR InsertRequest(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  InsertRequest(const InsertRequest& from);
  InsertRequest(InsertRequest&& from) noexcept
    : InsertRequest() {
    *this = ::std::move(from);
  }

  inline InsertRequest& operator=(const InsertRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline InsertRequest& operator=(InsertRequest&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const InsertRequest& default_instance() {
    return *internal_default_instance();
  }
  static inline const InsertRequest* internal_default_instance() {
    return reinterpret_cast<const InsertRequest*>(
               &_InsertRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(InsertRequest& a, InsertRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(InsertRequest* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(InsertRequest* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  InsertRequest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<InsertRequest>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const InsertRequest& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const InsertRequest& from) {
    InsertRequest::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(InsertRequest* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "vecdb.InsertRequest";
  }
  protected:
  explicit InsertRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kVectorFieldNumber = 2,
    kMetadataFieldNumber = 3,
    kVectorIdFieldNumber = 1,
  };
  // bytes vector = 2;
  void clear_vector();
  const std::string& vector() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_vector(ArgT0&& arg0, ArgT... args);
  std::string* mutable_vector();
  PROTOBUF_NODISCARD std::string* release_vector();
  void set_allocated_vector(std::string* vector);
  private:
  const std::string& _internal_vector() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_vector(const std::string& value);
  std::string* _internal_mutable_vector();
  public:

  // bytes metadata = 3;
  void clear_metadata();
  const std::string& metadata() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_metadata(ArgT0&& arg0, ArgT... args);
  std::string* mutable_metadata();
  PROTOBUF_NODISCARD std::string* release_metadata();
  void set_allocated_metadata(std::string* metadata);
  private:
  const std::string& _internal_metadata() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_metadata(const std::string& value);
  std::string* _internal_mutable_metadata();
  public:

  // uint64 vector_id = 1;
  void clear_vector_id();
  uint64_t vector_id() const;
  void set_vector_id(uint64_t value);
  private:
  uint64_t _internal_vector_id() const;
  void _internal_set_vector_id(uint64_t value);
  public:

  // @@protoc_insertion_point(class_scope:vecdb.InsertRequest)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr vector_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr metadata_;
    uint64_t vector_id_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_vecdb_2eproto;
};
// -------------------------------------------------------------------

class InsertResponse final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:vecdb.InsertResponse) */ {
 public:
  inline InsertResponse() : InsertResponse(nullptr) {}
  ~InsertResponse() override;
  explicit PROTOBUF_CONSTEXPR InsertResponse(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  InsertResponse(const InsertResponse& from);
  InsertResponse(InsertResponse&& from) noexcept
    : InsertResponse() {
    *this = ::std::move(from);
  }

  inline InsertResponse& operator=(const InsertResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline InsertResponse& operator=(InsertResponse&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const InsertResponse& default_instance() {
    return *internal_default_instance();
  }
  static inline const InsertResponse* internal_default_instance() {
    return reinterpret_cast<const InsertResponse*>(
               &_InsertResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(InsertResponse& a, InsertResponse& b) {
    a.Swap(&b);
  }
  inline void Swap(InsertResponse* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(InsertResponse* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  InsertResponse* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<InsertResponse>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const InsertResponse& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const InsertResponse& from) {
    InsertResponse::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(InsertResponse* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "vecdb.InsertResponse";
  }
  protected:
  explicit InsertResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kShardIdFieldNumber = 1,
    kNodeIdFieldNumber = 2,
    kLatencyUsFieldNumber = 3,
  };
  // uint32 shard_id = 1;
  void clear_shard_id();
  uint32_t shard_id() const;
  void set_shard_id(uint32_t value);
  private:
  uint32_t _internal_shard_id() const;
  void _internal_set_shard_id(uint32_t value);
  public:

  // uint32 node_id = 2;
  void clear_node_id();
  uint32_t node_id() const;
  void set_node_id(uint32_t value);
  private:
  uint32_t _internal_node_id() const;
  void _internal_set_node_id(uint32_t value);
  public:

  // int64 latency_us = 3;
  void clear_latency_us();
  int64_t latency_us() const;
  void set_latency_us(int64_t value);
  private:
  int64_t _internal_latency_us() const;
  void _internal_set_latency_us(int64_t value);
  public:

  // @@protoc_insertion_point(class_scope:vecdb.InsertResponse)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    uint32_t shard_id_;
    uint32_t node_id_;
    int64_t latency_us_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_vecdb_2eproto;
};
// -------------------------------------------------------------------

class BulkInsertResponse final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:vecdb.BulkInsertResponse) */ {
 public:
  inline BulkInsertResponse() : BulkInsertResponse(nullptr) {}
  ~BulkInsertResponse() override;
  explicit PROTOBUF_CONSTEXPR BulkInsertResponse(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  BulkInsertResponse(const BulkInsertResponse& from);
  BulkInsertResponse(BulkInsertResponse&& from) noexcept
    : BulkInsertResponse() {
    *this = ::std::move(from);
  }

  inline BulkInsertResponse& operator=(const BulkInsertResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline BulkInsertResponse& operator=(BulkInsertResponse&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const BulkInsertResponse& default_instance() {
    return *internal_default_instance();
  }
  static inline const BulkInsertResponse* internal_default_instance() {
    return reinterpret_cast<const BulkInsertResponse*>(
               &_BulkInsertResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(BulkInsertResponse& a, BulkInsertResponse& b) {
    a.Swap(&b);
  }
  inline void Swap(BulkInsertResponse* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(BulkInsertResponse* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  BulkInsertResponse* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<BulkInsertResponse>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const BulkInsertResponse& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const BulkInsertResponse& from) {
    BulkInsertResponse::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(BulkInsertResponse* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "vecdb.BulkInsertResponse";
  }
  protected:
  explicit BulkInsertResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kInsertedFieldNumber = 1,
    kFailedFieldNumber = 2,
    kLatencyUsFieldNumber = 3,
  };
  // uint64 inserted = 1;
  void clear_inserted();
  uint64_t inserted() const;
  void set_inserted(uint64_t value);
  private:
  uint64_t _internal_inserted() const;
  void _internal_set_inserted(uint64_t value);
  public:

  // uint64 failed = 2;
  void clear_failed();
  uint64_t failed() const;
  void set_failed(uint64_t value);
  private:
  uint64_t _internal_failed() const;
  void _internal_set_failed(uint64_t value);
  public:

  // int64 latency_us = 3;
  void clear_latency_us();
  int64_t latency_us() const;
  void set_latency_us(int64_t value);
  private:
  int64_t _internal_latency_us() const;
  void _internal_set_latency_us(int64_t value);
  public:

  // @@protoc_insertion_point(class_scope:vecdb.BulkInsertResponse)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    uint64_t inserted_;
    uint64_t failed_;
    int64_t latency_us_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_vecdb_2eproto;
};
// -------------------------------------------------------------------

class SearchRequest final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:vecdb.SearchRequest) */ {
 public:
  inline SearchRequest() : SearchRequest(nullptr) {}
  ~SearchRequest() override;
  explicit PROTOBUF_CONSTEXPR SearchRequest(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  SearchRequest(const SearchRequest& from);
  SearchRequest(SearchRequest&& from) noexcept
    : SearchRequest() {
    *this = ::std::move(from);
  }

  inline SearchRequest& operator=(const SearchRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline SearchRequest& operator=(SearchRequest&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const SearchRequest& default_instance() {
    return *internal_default_instance();
  }
  static inline const SearchRequest* internal_default_instance() {
    return reinterpret_cast<const SearchRequest*>(
               &_SearchRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(SearchRequest& a, SearchRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(SearchRequest* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(SearchRequest* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  SearchRequest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<SearchRequest>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const SearchRequest& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const SearchRequest& from) {
    SearchRequest::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(SearchRequest* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "vecdb.SearchRequest";
  }
  protected:
  explicit SearchRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kQueryFieldNumber = 1,
    kTopKFieldNumber = 2,
    kEfSearchFieldNumber = 3,
  };
  // bytes query = 1;
  void clear_query();
  const std::string& query() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_query(ArgT0&& arg0, ArgT... args);
  std::string* mutable_query();
  PROTOBUF_NODISCARD std::string* release_query();
  void set_allocated_query(std::string* query);
  private:
  const std::string& _internal_query() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_query(const std::string& value);
  std::string* _internal_mutable_query();
  public:

  // int32 top_k = 2;
  void clear_top_k();
  int32_t top_k() const;
  void set_top_k(int32_t value);
  private:
  int32_t _internal_top_k() const;
  void _internal_set_top_k(int32_t value);
  public:

  // int32 ef_search = 3;
  void clear_ef_search();
  int32_t ef_search() const;
  void set_ef_search(int32_t value);
  private:
  int32_t _internal_ef_search() const;
  void _internal_set_ef_search(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:vecdb.SearchRequest)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr query_;
    int32_t top_k_;
    int32_t ef_search_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_vecdb_2eproto;
};
// -------------------------------------------------------------------

class SearchResult final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:vecdb.SearchResult) */ {
 public:
  inline SearchResult() : SearchResult(nullptr) {}
  ~SearchResult() override;
  explicit PROTOBUF_CONSTEXPR SearchResult(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  SearchResult(const SearchResult& from);
  SearchResult(SearchResult&& from) noexcept
    : SearchResult() {
    *this = ::std::move(from);
  }

  inline SearchResult& operator=(const SearchResult& from) {
    CopyFrom(from);
    return *this;
  }
  inline SearchResult& operator=(SearchResult&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const SearchResult& default_instance() {
    return *internal_default_instance();
  }
  static inline const SearchResult* internal_default_instance() {
    return reinterpret_cast<const SearchResult*>(
               &_SearchResult_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    4;

  friend void swap(SearchResult& a, SearchResult& b) {
    a.Swap(&b);
  }
  inline void Swap(SearchResult* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(SearchResult* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  SearchResult* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<SearchResult>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const SearchResult& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const SearchResult& from) {
    SearchResult::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(SearchResult* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "vecdb.SearchResult";
  }
  protected:
  explicit SearchResult(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kMetadataFieldNumber = 4,
    kShardIdFieldNumber = 1,
    kNodeIdFieldNumber = 2,
    kDistanceFieldNumber = 3,
  };
  // bytes metadata = 4;
  void clear_metadata();
  const std::string& metadata() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_metadata(ArgT0&& arg0, ArgT... args);
  std::string* mutable_metadata();
  PROTOBUF_NODISCARD std::string* release_metadata();
  void set_allocated_metadata(std::string* metadata);
  private:
  const std::string& _internal_metadata() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_metadata(const std::string& value);
  std::string* _internal_mutable_metadata();
  public:

  // uint32 shard_id = 1;
  void clear_shard_id();
  uint32_t shard_id() const;
  void set_shard_id(uint32_t value);
  private:
  uint32_t _internal_shard_id() const;
  void _internal_set_shard_id(uint32_t value);
  public:

  // uint32 node_id = 2;
  void clear_node_id();
  uint32_t node_id() const;
  void set_node_id(uint32_t value);
  private:
  uint32_t _internal_node_id() const;
  void _internal_set_node_id(uint32_t value);
  public:

  // float distance = 3;
  void clear_distance();
  float distance() const;
  void set_distance(float value);
  private:
  float _internal_distance() const;
  void _internal_set_distance(float value);
  public:

  // @@protoc_insertion_point(class_scope:vecdb.SearchResult)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr metadata_;
    uint32_t shard_id_;
    uint32_t node_id_;
    float distance_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_vecdb_2eproto;
};
// -------------------------------------------------------------------

class SearchResponse final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:vecdb.SearchResponse) */ {
 public:
  inline SearchResponse() : SearchResponse(nullptr) {}
  ~SearchResponse() override;
  explicit PROTOBUF_CONSTEXPR SearchResponse(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  SearchResponse(const SearchResponse& from);
  SearchResponse(SearchResponse&& from) noexcept
    : SearchResponse() {
    *this = ::std::move(from);
  }

  inline SearchResponse& operator=(const SearchResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline SearchResponse& operator=(SearchResponse&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const SearchResponse& default_instance() {
    return *internal_default_instance();
  }
  static inline const SearchResponse* internal_default_instance() {
    return reinterpret_cast<const SearchResponse*>(
               &_SearchResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    5;

  friend void swap(SearchResponse& a, SearchResponse& b) {
    a.Swap(&b);
  }
  inline void Swap(SearchResponse* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(SearchResponse* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  SearchResponse* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<SearchResponse>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const SearchResponse& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const SearchResponse& from) {
    SearchResponse::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(SearchResponse* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "vecdb.SearchResponse";
  }
  protected:
  explicit SearchResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kResultsFieldNumber = 1,
    kLatencyUsFieldNumber = 2,
    kDegradedFieldNumber = 3,
    kShardsOkFieldNumber = 4,
    kShardsErrFieldNumber = 5,
  };
  // repeated .vecdb.SearchResult results = 1;
  int results_size() const;
  private:
  int _internal_results_size() const;
  public:
  void clear_results();
  ::vecdb::SearchResult* mutable_results(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::vecdb::SearchResult >*
      mutable_results();
  private:
  const ::vecdb::SearchResult& _internal_results(int index) const;
  ::vecdb::SearchResult* _internal_add_results();
  public:
  const ::vecdb::SearchResult& results(int index) const;
  ::vecdb::SearchResult* add_results();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::vecdb::SearchResult >&
      results() const;

  // int64 latency_us = 2;
  void clear_latency_us();
  int64_t latency_us() const;
  void set_latency_us(int64_t value);
  private:
  int64_t _internal_latency_us() const;
  void _internal_set_latency_us(int64_t value);
  public:

  // bool degraded = 3;
  void clear_degraded();
  bool degraded() const;
  void set_degraded(bool value);
  private:
  bool _internal_degraded() const;
  void _internal_set_degraded(bool value);
  public:

  // uint32 shards_ok = 4;
  void clear_shards_ok();
  uint32_t shards_ok() const;
  void set_shards_ok(uint32_t value);
  private:
  uint32_t _internal_shards_ok() const;
  void _internal_set_shards_ok(uint32_t value);
  public:

  // uint32 shards_err = 5;
  void clear_shards_err();
  uint32_t shards_err() const;
  void set_shards_err(uint32_t value);
  private:
  uint32_t _internal_shards_err() const;
  void _internal_set_shards_err(uint32_t value);
  public:

  // @@protoc_insertion_point(class_scope:vecdb.SearchResponse)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::vecdb::SearchResult > results_;
    int64_t latency_us_;
    bool degraded_;
    uint32_t shards_ok_;
    uint32_t shards_err_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_vecdb_2eproto;
};
// -------------------------------------------------------------------

class DeleteRequest final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:vecdb.DeleteRequest) */ {
 public:
  inline DeleteRequest() : DeleteRequest(nullptr) {}
  ~DeleteRequest() override;
  explicit PROTOBUF_CONSTEXPR DeleteRequest(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  DeleteRequest(const DeleteRequest& from);
  DeleteRequest(DeleteRequest&& from) noexcept
    : DeleteRequest() {
    *this = ::std::move(from);
  }

  inline DeleteRequest& operator=(const DeleteRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline DeleteRequest& operator=(DeleteRequest&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const DeleteRequest& default_instance() {
    return *internal_default_instance();
  }
  static inline const DeleteRequest* internal_default_instance() {
    return reinterpret_cast<const DeleteRequest*>(
               &_DeleteRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    6;

  friend void swap(DeleteRequest& a, DeleteRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(DeleteRequest* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(DeleteRequest* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  DeleteRequest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<DeleteRequest>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const DeleteRequest& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const DeleteRequest& from) {
    DeleteRequest::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(DeleteRequest* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "vecdb.DeleteRequest";
  }
  protected:
  explicit DeleteRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kVectorIdFieldNumber = 1,
  };
  // uint64 vector_id = 1;
  void clear_vector_id();
  uint64_t vector_id() const;
  void set_vector_id(uint64_t value);
  private:
  uint64_t _internal_vector_id() const;
  void _internal_set_vector_id(uint64_t value);
  public:

  // @@protoc_insertion_point(class_scope:vecdb.DeleteRequest)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    uint64_t vector_id_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_vecdb_2eproto;
};
// -------------------------------------------------------------------

class DeleteResponse final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:vecdb.DeleteResponse) */ {
 public:
  inline DeleteResponse() : DeleteResponse(nullptr) {}
  ~DeleteResponse() override;
  explicit PROTOBUF_CONSTEXPR DeleteResponse(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  DeleteResponse(const DeleteResponse& from);
  DeleteResponse(DeleteResponse&& from) noexcept
    : DeleteResponse() {
    *this = ::std::move(from);
  }

  inline DeleteResponse& operator=(const DeleteResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline DeleteResponse& operator=(DeleteResponse&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const DeleteResponse& default_instance() {
    return *internal_default_instance();
  }
  static inline const DeleteResponse* internal_default_instance() {
    return reinterpret_cast<const DeleteResponse*>(
               &_DeleteResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    7;

  friend void swap(DeleteResponse& a, DeleteResponse& b) {
    a.Swap(&b);
  }
  inline void Swap(DeleteResponse* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(DeleteResponse* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  DeleteResponse* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<DeleteResponse>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const DeleteResponse& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const DeleteResponse& from) {
    DeleteResponse::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(DeleteResponse* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "vecdb.DeleteResponse";
  }
  protected:
  explicit DeleteResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kLatencyUsFieldNumber = 2,
    kFoundFieldNumber = 1,
  };
  // int64 latency_us = 2;
  void clear_latency_us();
  int64_t latency_us() const;
  void set_latency_us(int64_t value);
  private:
  int64_t _internal_latency_us() const;
  void _internal_set_latency_us(int64_t value);
  public:

  // bool found = 1;
  void clear_found();
  bool found() const;
  void set_found(bool value);
  private:
  bool _internal_found() const;
  void _internal_set_found(bool value);
  public:

  // @@protoc_insertion_point(class_scope:vecdb.DeleteResponse)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    int64_t latency_us_;
    bool found_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_vecdb_2eproto;
};
// -------------------------------------------------------------------

class InfoRequest final :
    public ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase /* @@protoc_insertion_point(class_definition:vecdb.InfoRequest) */ {
 public:
  inline InfoRequest() : InfoRequest(nullptr) {}
  explicit PROTOBUF_CONSTEXPR InfoRequest(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  InfoRequest(const InfoRequest& from);
  InfoRequest(InfoRequest&& from) noexcept
    : InfoRequest() {
    *this = ::std::move(from);
  }

  inline InfoRequest& operator=(const InfoRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline InfoRequest& operator=(InfoRequest&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const InfoRequest& default_instance() {
    return *internal_default_instance();
  }
  static inline const InfoRequest* internal_default_instance() {
    return reinterpret_cast<const InfoRequest*>(
               &_InfoRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    8;

  friend void swap(InfoRequest& a, InfoRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(InfoRequest* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(InfoRequest* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  InfoRequest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<InfoRequest>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::CopyFrom;
  inline void CopyFrom(const InfoRequest& from) {
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::CopyImpl(*this, from);
  }
  using ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::MergeFrom;
  void MergeFrom(const InfoRequest& from) {
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::MergeImpl(*this, from);
  }
  public:

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "vecdb.InfoRequest";
  }
  protected:
  explicit InfoRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:vecdb.InfoRequest)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
  };
  friend struct ::TableStruct_vecdb_2eproto;
};
// -------------------------------------------------------------------

class ShardInfo final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:vecdb.ShardInfo) */ {
 public:
  inline ShardInfo() : ShardInfo(nullptr) {}
  ~ShardInfo() override;
  explicit PROTOBUF_CONSTEXPR ShardInfo(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  ShardInfo(const ShardInfo& from);
  ShardInfo(ShardInfo&& from) noexcept
    : ShardInfo() {
    *this = ::std::move(from);
  }

  inline ShardInfo& operator=(const ShardInfo& from) {
    CopyFrom(from);
    return *this;
  }
  inline ShardInfo& operator=(ShardInfo&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ShardInfo& default_instance() {
    return *internal_default_instance();
  }
  static inline const ShardInfo* internal_default_instance() {
    return reinterpret_cast<const ShardInfo*>(
               &_ShardInfo_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    9;

  friend void swap(ShardInfo& a, ShardInfo& b) {
    a.Swap(&b);
  }
  inline void Swap(ShardInfo* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ShardInfo* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ShardInfo* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<ShardInfo>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const ShardInfo& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const ShardInfo& from) {
    ShardInfo::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ShardInfo* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "vecdb.ShardInfo";
  }
  protected:
  explicit ShardInfo(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kStatusFieldNumber = 3,
    kVectorCountFieldNumber = 2,
    kShardIdFieldNumber = 1,
  };
  // string status = 3;
  void clear_status();
  const std::string& status() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_status(ArgT0&& arg0, ArgT... args);
  std::string* mutable_status();
  PROTOBUF_NODISCARD std::string* release_status();
  void set_allocated_status(std::string* status);
  private:
  const std::string& _internal_status() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_status(const std::string& value);
  std::string* _internal_mutable_status();
  public:

  // uint64 vector_count = 2;
  void clear_vector_count();
  uint64_t vector_count() const;
  void set_vector_count(uint64_t value);
  private:
  uint64_t _internal_vector_count() const;
  void _internal_set_vector_count(uint64_t value);
  public:

  // uint32 shard_id = 1;
  void clear_shard_id();
  uint32_t shard_id() const;
  void set_shard_id(uint32_t value);
  private:
  uint32_t _internal_shard_id() const;
  void _internal_set_shard_id(uint32_t value);
  public:

  // @@protoc_insertion_point(class_scope:vecdb.ShardInfo)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr status_;
    uint64_t vector_count_;
    uint32_t shard_id_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_vecdb_2eproto;
};
// -------------------------------------------------------------------

class InfoResponse final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:vecdb.InfoResponse) */ {
 public:
  inline InfoResponse() : InfoResponse(nullptr) {}
  ~InfoResponse() override;
  explicit PROTOBUF_CONSTEXPR InfoResponse(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  InfoResponse(const InfoResponse& from);
  InfoResponse(InfoResponse&& from) noexcept
    : InfoResponse() {
    *this = ::std::move(from);
  }

  inline InfoResponse& operator=(const InfoResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline InfoResponse& operator=(InfoResponse&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const InfoResponse& default_instance() {
    return *internal_default_instance();
  }
  static inline const InfoResponse* internal_default_instance() {
    return reinterpret_cast<const InfoResponse*>(
               &_InfoResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    10;

  friend void swap(InfoResponse& a, InfoResponse& b) {
    a.Swap(&b);
  }
  inline void Swap(InfoResponse* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(InfoResponse* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  InfoResponse* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<InfoResponse>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const InfoResponse& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const InfoResponse& from) {
    InfoResponse::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(InfoResponse* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "vecdb.InfoResponse";
  }
  protected:
  explicit InfoResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kShardsFieldNumber = 4,
    kTotalVectorsFieldNumber = 1,
    kShardCountFieldNumber = 2,
    kDimFieldNumber = 3,
  };
  // repeated .vecdb.ShardInfo shards = 4;
  int shards_size() const;
  private:
  int _internal_shards_size() const;
  public:
  void clear_shards();
  ::vecdb::ShardInfo* mutable_shards(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::vecdb::ShardInfo >*
      mutable_shards();
  private:
  const ::vecdb::ShardInfo& _internal_shards(int index) const;
  ::vecdb::ShardInfo* _internal_add_shards();
  public:
  const ::vecdb::ShardInfo& shards(int index) const;
  ::vecdb::ShardInfo* add_shards();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::vecdb::ShardInfo >&
      shards() const;

  // uint64 total_vectors = 1;
  void clear_total_vectors();
  uint64_t total_vectors() const;
  void set_total_vectors(uint64_t value);
  private:
  uint64_t _internal_total_vectors() const;
  void _internal_set_total_vectors(uint64_t value);
  public:

  // uint32 shard_count = 2;
  void clear_shard_count();
  uint32_t shard_count() const;
  void set_shard_count(uint32_t value);
  private:
  uint32_t _internal_shard_count() const;
  void _internal_set_shard_count(uint32_t value);
  public:

  // int32 dim = 3;
  void clear_dim();
  int32_t dim() const;
  void set_dim(int32_t value);
  private:
  int32_t _internal_dim() const;
  void _internal_set_dim(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:vecdb.InfoResponse)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::vecdb::ShardInfo > shards_;
    uint64_t total_vectors_;
    uint32_t shard_count_;
    int32_t dim_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_vecdb_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// InsertRequest

// uint64 vector_id = 1;
inline void InsertRequest::clear_vector_id() {
  _impl_.vector_id_ = uint64_t{0u};
}
inline uint64_t InsertRequest::_internal_vector_id() const {
  return _impl_.vector_id_;
}
inline uint64_t InsertRequest::vector_id() const {
  // @@protoc_insertion_point(field_get:vecdb.InsertRequest.vector_id)
  return _internal_vector_id();
}
inline void InsertRequest::_internal_set_vector_id(uint64_t value) {
  
  _impl_.vector_id_ = value;
}
inline void InsertRequest::set_vector_id(uint64_t value) {
  _internal_set_vector_id(value);
  // @@protoc_insertion_point(field_set:vecdb.InsertRequest.vector_id)
}

// bytes vector = 2;
inline void InsertRequest::clear_vector() {
  _impl_.vector_.ClearToEmpty();
}
inline const std::string& InsertRequest::vector() const {
  // @@protoc_insertion_point(field_get:vecdb.InsertRequest.vector)
  return _internal_vector();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void InsertRequest::set_vector(ArgT0&& arg0, ArgT... args) {
 
 _impl_.vector_.SetBytes(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:vecdb.InsertRequest.vector)
}
inline std::string* InsertRequest::mutable_vector() {
  std::string* _s = _internal_mutable_vector();
  // @@protoc_insertion_point(field_mutable:vecdb.InsertRequest.vector)
  return _s;
}
inline const std::string& InsertRequest::_internal_vector() const {
  return _impl_.vector_.Get();
}
inline void InsertRequest::_internal_set_vector(const std::string& value) {
  
  _impl_.vector_.Set(value, GetArenaForAllocation());
}
inline std::string* InsertRequest::_internal_mutable_vector() {
  
  return _impl_.vector_.Mutable(GetArenaForAllocation());
}
inline std::string* InsertRequest::release_vector() {
  // @@protoc_insertion_point(field_release:vecdb.InsertRequest.vector)
  return _impl_.vector_.Release();
}
inline void InsertRequest::set_allocated_vector(std::string* vector) {
  if (vector != nullptr) {
    
  } else {
    
  }
  _impl_.vector_.SetAllocated(vector, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.vector_.IsDefault()) {
    _impl_.vector_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:vecdb.InsertRequest.vector)
}

// bytes metadata = 3;
inline void InsertRequest::clear_metadata() {
  _impl_.metadata_.ClearToEmpty();
}
inline const std::string& InsertRequest::metadata() const {
  // @@protoc_insertion_point(field_get:vecdb.InsertRequest.metadata)
  return _internal_metadata();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void InsertRequest::set_metadata(ArgT0&& arg0, ArgT... args) {
 
 _impl_.metadata_.SetBytes(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:vecdb.InsertRequest.metadata)
}
inline std::string* InsertRequest::mutable_metadata() {
  std::string* _s = _internal_mutable_metadata();
  // @@protoc_insertion_point(field_mutable:vecdb.InsertRequest.metadata)
  return _s;
}
inline const std::string& InsertRequest::_internal_metadata() const {
  return _impl_.metadata_.Get();
}
inline void InsertRequest::_internal_set_metadata(const std::string& value) {
  
  _impl_.metadata_.Set(value, GetArenaForAllocation());
}
inline std::string* InsertRequest::_internal_mutable_metadata() {
  
  return _impl_.metadata_.Mutable(GetArenaForAllocation());
}
inline std::string* InsertRequest::release_metadata() {
  // @@protoc_insertion_point(field_release:vecdb.InsertRequest.metadata)
  return _impl_.metadata_.Release();
}
inline void InsertRequest::set_allocated_metadata(std::string* metadata) {
  if (metadata != nullptr) {
    
  } else {
    
  }
  _impl_.metadata_.SetAllocated(metadata, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.metadata_.IsDefault()) {
    _impl_.metadata_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:vecdb.InsertRequest.metadata)
}

// -------------------------------------------------------------------

// InsertResponse

// uint32 shard_id = 1;
inline void InsertResponse::clear_shard_id() {
  _impl_.shard_id_ = 0u;
}
inline uint32_t InsertResponse::_internal_shard_id() const {
  return _impl_.shard_id_;
}
inline uint32_t InsertResponse::shard_id() const {
  // @@protoc_insertion_point(field_get:vecdb.InsertResponse.shard_id)
  return _internal_shard_id();
}
inline void InsertResponse::_internal_set_shard_id(uint32_t value) {
  
  _impl_.shard_id_ = value;
}
inline void InsertResponse::set_shard_id(uint32_t value) {
  _internal_set_shard_id(value);
  // @@protoc_insertion_point(field_set:vecdb.InsertResponse.shard_id)
}

// uint32 node_id = 2;
inline void InsertResponse::clear_node_id() {
  _impl_.node_id_ = 0u;
}
inline uint32_t InsertResponse::_internal_node_id() const {
  return _impl_.node_id_;
}
inline uint32_t InsertResponse::node_id() const {
  // @@protoc_insertion_point(field_get:vecdb.InsertResponse.node_id)
  return _internal_node_id();
}
inline void InsertResponse::_internal_set_node_id(uint32_t value) {
  
  _impl_.node_id_ = value;
}
inline void InsertResponse::set_node_id(uint32_t value) {
  _internal_set_node_id(value);
  // @@protoc_insertion_point(field_set:vecdb.InsertResponse.node_id)
}

// int64 latency_us = 3;
inline void InsertResponse::clear_latency_us() {
  _impl_.latency_us_ = int64_t{0};
}
inline int64_t InsertResponse::_internal_latency_us() const {
  return _impl_.latency_us_;
}
inline int64_t InsertResponse::latency_us() const {
  // @@protoc_insertion_point(field_get:vecdb.InsertResponse.latency_us)
  return _internal_latency_us();
}
inline void InsertResponse::_internal_set_latency_us(int64_t value) {
  
  _impl_.latency_us_ = value;
}
inline void InsertResponse::set_latency_us(int64_t value) {
  _internal_set_latency_us(value);
  // @@protoc_insertion_point(field_set:vecdb.InsertResponse.latency_us)
}

// -------------------------------------------------------------------

// BulkInsertResponse

// uint64 inserted = 1;
inline void BulkInsertResponse::clear_inserted() {
  _impl_.inserted_ = uint64_t{0u};
}
inline uint64_t BulkInsertResponse::_internal_inserted() const {
  return _impl_.inserted_;
}
inline uint64_t BulkInsertResponse::inserted() const {
  // @@protoc_insertion_point(field_get:vecdb.BulkInsertResponse.inserted)
  return _internal_inserted();
}
inline void BulkInsertResponse::_internal_set_inserted(uint64_t value) {
  
  _impl_.inserted_ = value;
}
inline void BulkInsertResponse::set_inserted(uint64_t value) {
  _internal_set_inserted(value);
  // @@protoc_insertion_point(field_set:vecdb.BulkInsertResponse.inserted)
}

// uint64 failed = 2;
inline void BulkInsertResponse::clear_failed() {
  _impl_.failed_ = uint64_t{0u};
}
inline uint64_t BulkInsertResponse::_internal_failed() const {
  return _impl_.failed_;
}
inline uint64_t BulkInsertResponse::failed() const {
  // @@protoc_insertion_point(field_get:vecdb.BulkInsertResponse.failed)
  return _internal_failed();
}
inline void BulkInsertResponse::_internal_set_failed(uint64_t value) {
  
  _impl_.failed_ = value;
}
inline void BulkInsertResponse::set_failed(uint64_t value) {
  _internal_set_failed(value);
  // @@protoc_insertion_point(field_set:vecdb.BulkInsertResponse.failed)
}

// int64 latency_us = 3;
inline void BulkInsertResponse::clear_latency_us() {
  _impl_.latency_us_ = int64_t{0};
}
inline int64_t BulkInsertResponse::_internal_latency_us() const {
  return _impl_.latency_us_;
}
inline int64_t BulkInsertResponse::latency_us() const {
  // @@protoc_insertion_point(field_get:vecdb.BulkInsertResponse.latency_us)
  return _internal_latency_us();
}
inline void BulkInsertResponse::_internal_set_latency_us(int64_t value) {
  
  _impl_.latency_us_ = value;
}
inline void BulkInsertResponse::set_latency_us(int64_t value) {
  _internal_set_latency_us(value);
  // @@protoc_insertion_point(field_set:vecdb.BulkInsertResponse.latency_us)
}

// -------------------------------------------------------------------

// SearchRequest

// bytes query = 1;
inline void SearchRequest::clear_query() {
  _impl_.query_.ClearToEmpty();
}
inline const std::string& SearchRequest::query() const {
  // @@protoc_insertion_point(field_get:vecdb.SearchRequest.query)
  return _internal_query();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void SearchRequest::set_query(ArgT0&& arg0, ArgT... args) {
 
 _impl_.query_.SetBytes(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:vecdb.SearchRequest.query)
}
inline std::string* SearchRequest::mutable_query() {
  std::string* _s = _internal_mutable_query();
  // @@protoc_insertion_point(field_mutable:vecdb.SearchRequest.query)
  return _s;
}
inline const std::string& SearchRequest::_internal_query() const {
  return _impl_.query_.Get();
}
inline void SearchRequest::_internal_set_query(const std::string& value) {
  
  _impl_.query_.Set(value, GetArenaForAllocation());
}
inline std::string* SearchRequest::_internal_mutable_query() {
  
  return _impl_.query_.Mutable(GetArenaForAllocation());
}
inline std::string* SearchRequest::release_query() {
  // @@protoc_insertion_point(field_release:vecdb.SearchRequest.query)
  return _impl_.query_.Release();
}
inline void SearchRequest::set_allocated_query(std::string* query) {
  if (query != nullptr) {
    
  } else {
    
  }
  _impl_.query_.SetAllocated(query, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.query_.IsDefault()) {
    _impl_.query_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:vecdb.SearchRequest.query)
}

// int32 top_k = 2;
inline void SearchRequest::clear_top_k() {
  _impl_.top_k_ = 0;
}
inline int32_t SearchRequest::_internal_top_k() const {
  return _impl_.top_k_;
}
inline int32_t SearchRequest::top_k() const {
  // @@protoc_insertion_point(field_get:vecdb.SearchRequest.top_k)
  return _internal_top_k();
}
inline void SearchRequest::_internal_set_top_k(int32_t value) {
  
  _impl_.top_k_ = value;
}
inline void SearchRequest::set_top_k(int32_t value) {
  _internal_set_top_k(value);
  // @@protoc_insertion_point(field_set:vecdb.SearchRequest.top_k)
}

// int32 ef_search = 3;
inline void SearchRequest::clear_ef_search() {
  _impl_.ef_search_ = 0;
}
inline int32_t SearchRequest::_internal_ef_search() const {
  return _impl_.ef_search_;
}
inline int32_t SearchRequest::ef_search() const {
  // @@protoc_insertion_point(field_get:vecdb.SearchRequest.ef_search)
  return _internal_ef_search();
}
inline void SearchRequest::_internal_set_ef_search(int32_t value) {
  
  _impl_.ef_search_ = value;
}
inline void SearchRequest::set_ef_search(int32_t value) {
  _internal_set_ef_search(value);
  // @@protoc_insertion_point(field_set:vecdb.SearchRequest.ef_search)
}

// -------------------------------------------------------------------

// SearchResult

// uint32 shard_id = 1;
inline void SearchResult::clear_shard_id() {
  _impl_.shard_id_ = 0u;
}
inline uint32_t SearchResult::_internal_shard_id() const {
  return _impl_.shard_id_;
}
inline uint32_t SearchResult::shard_id() const {
  // @@protoc_insertion_point(field_get:vecdb.SearchResult.shard_id)
  return _internal_shard_id();
}
inline void SearchResult::_internal_set_shard_id(uint32_t value) {
  
  _impl_.shard_id_ = value;
}
inline void SearchResult::set_shard_id(uint32_t value) {
  _internal_set_shard_id(value);
  // @@protoc_insertion_point(field_set:vecdb.SearchResult.shard_id)
}

// uint32 node_id = 2;
inline void SearchResult::clear_node_id() {
  _impl_.node_id_ = 0u;
}
inline uint32_t SearchResult::_internal_node_id() const {
  return _impl_.node_id_;
}
inline uint32_t SearchResult::node_id() const {
  // @@protoc_insertion_point(field_get:vecdb.SearchResult.node_id)
  return _internal_node_id();
}
inline void SearchResult::_internal_set_node_id(uint32_t value) {
  
  _impl_.node_id_ = value;
}
inline void SearchResult::set_node_id(uint32_t value) {
  _internal_set_node_id(value);
  // @@protoc_insertion_point(field_set:vecdb.SearchResult.node_id)
}

// float distance = 3;
inline void SearchResult::clear_distance() {
  _impl_.distance_ = 0;
}
inline float SearchResult::_internal_distance() const {
  return _impl_.distance_;
}
inline float SearchResult::distance() const {
  // @@protoc_insertion_point(field_get:vecdb.SearchResult.distance)
  return _internal_distance();
}
inline void SearchResult::_internal_set_distance(float value) {
  
  _impl_.distance_ = value;
}
inline void SearchResult::set_distance(float value) {
  _internal_set_distance(value);
  // @@protoc_insertion_point(field_set:vecdb.SearchResult.distance)
}

// bytes metadata = 4;
inline void SearchResult::clear_metadata() {
  _impl_.metadata_.ClearToEmpty();
}
inline const std::string& SearchResult::metadata() const {
  // @@protoc_insertion_point(field_get:vecdb.SearchResult.metadata)
  return _internal_metadata();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void SearchResult::set_metadata(ArgT0&& arg0, ArgT... args) {
 
 _impl_.metadata_.SetBytes(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:vecdb.SearchResult.metadata)
}
inline std::string* SearchResult::mutable_metadata() {
  std::string* _s = _internal_mutable_metadata();
  // @@protoc_insertion_point(field_mutable:vecdb.SearchResult.metadata)
  return _s;
}
inline const std::string& SearchResult::_internal_metadata() const {
  return _impl_.metadata_.Get();
}
inline void SearchResult::_internal_set_metadata(const std::string& value) {
  
  _impl_.metadata_.Set(value, GetArenaForAllocation());
}
inline std::string* SearchResult::_internal_mutable_metadata() {
  
  return _impl_.metadata_.Mutable(GetArenaForAllocation());
}
inline std::string* SearchResult::release_metadata() {
  // @@protoc_insertion_point(field_release:vecdb.SearchResult.metadata)
  return _impl_.metadata_.Release();
}
inline void SearchResult::set_allocated_metadata(std::string* metadata) {
  if (metadata != nullptr) {
    
  } else {
    
  }
  _impl_.metadata_.SetAllocated(metadata, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.metadata_.IsDefault()) {
    _impl_.metadata_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:vecdb.SearchResult.metadata)
}

// -------------------------------------------------------------------

// SearchResponse

// repeated .vecdb.SearchResult results = 1;
inline int SearchResponse::_internal_results_size() const {
  return _impl_.results_.size();
}
inline int SearchResponse::results_size() const {
  return _internal_results_size();
}
inline void SearchResponse::clear_results() {
  _impl_.results_.Clear();
}
inline ::vecdb::SearchResult* SearchResponse::mutable_results(int index) {
  // @@protoc_insertion_point(field_mutable:vecdb.SearchResponse.results)
  return _impl_.results_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::vecdb::SearchResult >*
SearchResponse::mutable_results() {
  // @@protoc_insertion_point(field_mutable_list:vecdb.SearchResponse.results)
  return &_impl_.results_;
}
inline const ::vecdb::SearchResult& SearchResponse::_internal_results(int index) const {
  return _impl_.results_.Get(index);
}
inline const ::vecdb::SearchResult& SearchResponse::results(int index) const {
  // @@protoc_insertion_point(field_get:vecdb.SearchResponse.results)
  return _internal_results(index);
}
inline ::vecdb::SearchResult* SearchResponse::_internal_add_results() {
  return _impl_.results_.Add();
}
inline ::vecdb::SearchResult* SearchResponse::add_results() {
  ::vecdb::SearchResult* _add = _internal_add_results();
  // @@protoc_insertion_point(field_add:vecdb.SearchResponse.results)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::vecdb::SearchResult >&
SearchResponse::results() const {
  // @@protoc_insertion_point(field_list:vecdb.SearchResponse.results)
  return _impl_.results_;
}

// int64 latency_us = 2;
inline void SearchResponse::clear_latency_us() {
  _impl_.latency_us_ = int64_t{0};
}
inline int64_t SearchResponse::_internal_latency_us() const {
  return _impl_.latency_us_;
}
inline int64_t SearchResponse::latency_us() const {
  // @@protoc_insertion_point(field_get:vecdb.SearchResponse.latency_us)
  return _internal_latency_us();
}
inline void SearchResponse::_internal_set_latency_us(int64_t value) {
  
  _impl_.latency_us_ = value;
}
inline void SearchResponse::set_latency_us(int64_t value) {
  _internal_set_latency_us(value);
  // @@protoc_insertion_point(field_set:vecdb.SearchResponse.latency_us)
}

// bool degraded = 3;
inline void SearchResponse::clear_degraded() {
  _impl_.degraded_ = false;
}
inline bool SearchResponse::_internal_degraded() const {
  return _impl_.degraded_;
}
inline bool SearchResponse::degraded() const {
  // @@protoc_insertion_point(field_get:vecdb.SearchResponse.degraded)
  return _internal_degraded();
}
inline void SearchResponse::_internal_set_degraded(bool value) {
  
  _impl_.degraded_ = value;
}
inline void SearchResponse::set_degraded(bool value) {
  _internal_set_degraded(value);
  // @@protoc_insertion_point(field_set:vecdb.SearchResponse.degraded)
}

// uint32 shards_ok = 4;
inline void SearchResponse::clear_shards_ok() {
  _impl_.shards_ok_ = 0u;
}
inline uint32_t SearchResponse::_internal_shards_ok() const {
  return _impl_.shards_ok_;
}
inline uint32_t SearchResponse::shards_ok() const {
  // @@protoc_insertion_point(field_get:vecdb.SearchResponse.shards_ok)
  return _internal_shards_ok();
}
inline void SearchResponse::_internal_set_shards_ok(uint32_t value) {
  
  _impl_.shards_ok_ = value;
}
inline void SearchResponse::set_shards_ok(uint32_t value) {
  _internal_set_shards_ok(value);
  // @@protoc_insertion_point(field_set:vecdb.SearchResponse.shards_ok)
}

// uint32 shards_err = 5;
inline void SearchResponse::clear_shards_err() {
  _impl_.shards_err_ = 0u;
}
inline uint32_t SearchResponse::_internal_shards_err() const {
  return _impl_.shards_err_;
}
inline uint32_t SearchResponse::shards_err() const {
  // @@protoc_insertion_point(field_get:vecdb.SearchResponse.shards_err)
  return _internal_shards_err();
}
inline void SearchResponse::_internal_set_shards_err(uint32_t value) {
  
  _impl_.shards_err_ = value;
}
inline void SearchResponse::set_shards_err(uint32_t value) {
  _internal_set_shards_err(value);
  // @@protoc_insertion_point(field_set:vecdb.SearchResponse.shards_err)
}

// -------------------------------------------------------------------

// DeleteRequest

// uint64 vector_id = 1;
inline void DeleteRequest::clear_vector_id() {
  _impl_.vector_id_ = uint64_t{0u};
}
inline uint64_t DeleteRequest::_internal_vector_id() const {
  return _impl_.vector_id_;
}
inline uint64_t DeleteRequest::vector_id() const {
  // @@protoc_insertion_point(field_get:vecdb.DeleteRequest.vector_id)
  return _internal_vector_id();
}
inline void DeleteRequest::_internal_set_vector_id(uint64_t value) {
  
  _impl_.vector_id_ = value;
}
inline void DeleteRequest::set_vector_id(uint64_t value) {
  _internal_set_vector_id(value);
  // @@protoc_insertion_point(field_set:vecdb.DeleteRequest.vector_id)
}

// -------------------------------------------------------------------

// DeleteResponse

// bool found = 1;
inline void DeleteResponse::clear_found() {
  _impl_.found_ = false;
}
inline bool DeleteResponse::_internal_found() const {
  return _impl_.found_;
}
inline bool DeleteResponse::found() const {
  // @@protoc_insertion_point(field_get:vecdb.DeleteResponse.found)
  return _internal_found();
}
inline void DeleteResponse::_internal_set_found(bool value) {
  
  _impl_.found_ = value;
}
inline void DeleteResponse::set_found(bool value) {
  _internal_set_found(value);
  // @@protoc_insertion_point(field_set:vecdb.DeleteResponse.found)
}

// int64 latency_us = 2;
inline void DeleteResponse::clear_latency_us() {
  _impl_.latency_us_ = int64_t{0};
}
inline int64_t DeleteResponse::_internal_latency_us() const {
  return _impl_.latency_us_;
}
inline int64_t DeleteResponse::latency_us() const {
  // @@protoc_insertion_point(field_get:vecdb.DeleteResponse.latency_us)
  return _internal_latency_us();
}
inline void DeleteResponse::_internal_set_latency_us(int64_t value) {
  
  _impl_.latency_us_ = value;
}
inline void DeleteResponse::set_latency_us(int64_t value) {
  _internal_set_latency_us(value);
  // @@protoc_insertion_point(field_set:vecdb.DeleteResponse.latency_us)
}

// -------------------------------------------------------------------

// InfoRequest

// -------------------------------------------------------------------

// ShardInfo

// uint32 shard_id = 1;
inline void ShardInfo::clear_shard_id() {
  _impl_.shard_id_ = 0u;
}
inline uint32_t ShardInfo::_internal_shard_id() const {
  return _impl_.shard_id_;
}
inline uint32_t ShardInfo::shard_id() const {
  // @@protoc_insertion_point(field_get:vecdb.ShardInfo.shard_id)
  return _internal_shard_id();
}
inline void ShardInfo::_internal_set_shard_id(uint32_t value) {
  
  _impl_.shard_id_ = value;
}
inline void ShardInfo::set_shard_id(uint32_t value) {
  _internal_set_shard_id(value);
  // @@protoc_insertion_point(field_set:vecdb.ShardInfo.shard_id)
}

// uint64 vector_count = 2;
inline void ShardInfo::clear_vector_count() {
  _impl_.vector_count_ = uint64_t{0u};
}
inline uint64_t ShardInfo::_internal_vector_count() const {
  return _impl_.vector_count_;
}
inline uint64_t ShardInfo::vector_count() const {
  // @@protoc_insertion_point(field_get:vecdb.ShardInfo.vector_count)
  return _internal_vector_count();
}
inline void ShardInfo::_internal_set_vector_count(uint64_t value) {
  
  _impl_.vector_count_ = value;
}
inline void ShardInfo::set_vector_count(uint64_t value) {
  _internal_set_vector_count(value);
  // @@protoc_insertion_point(field_set:vecdb.ShardInfo.vector_count)
}

// string status = 3;
inline void ShardInfo::clear_status() {
  _impl_.status_.ClearToEmpty();
}
inline const std::string& ShardInfo::status() const {
  // @@protoc_insertion_point(field_get:vecdb.ShardInfo.status)
  return _internal_status();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void ShardInfo::set_status(ArgT0&& arg0, ArgT... args) {
 
 _impl_.status_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:vecdb.ShardInfo.status)
}
inline std::string* ShardInfo::mutable_status() {
  std::string* _s = _internal_mutable_status();
  // @@protoc_insertion_point(field_mutable:vecdb.ShardInfo.status)
  return _s;
}
inline const std::string& ShardInfo::_internal_status() const {
  return _impl_.status_.Get();
}
inline void ShardInfo::_internal_set_status(const std::string& value) {
  
  _impl_.status_.Set(value, GetArenaForAllocation());
}
inline std::string* ShardInfo::_internal_mutable_status() {
  
  return _impl_.status_.Mutable(GetArenaForAllocation());
}
inline std::string* ShardInfo::release_status() {
  // @@protoc_insertion_point(field_release:vecdb.ShardInfo.status)
  return _impl_.status_.Release();
}
inline void ShardInfo::set_allocated_status(std::string* status) {
  if (status != nullptr) {
    
  } else {
    
  }
  _impl_.status_.SetAllocated(status, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.status_.IsDefault()) {
    _impl_.status_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:vecdb.ShardInfo.status)
}

// -------------------------------------------------------------------

// InfoResponse

// uint64 total_vectors = 1;
inline void InfoResponse::clear_total_vectors() {
  _impl_.total_vectors_ = uint64_t{0u};
}
inline uint64_t InfoResponse::_internal_total_vectors() const {
  return _impl_.total_vectors_;
}
inline uint64_t InfoResponse::total_vectors() const {
  // @@protoc_insertion_point(field_get:vecdb.InfoResponse.total_vectors)
  return _internal_total_vectors();
}
inline void InfoResponse::_internal_set_total_vectors(uint64_t value) {
  
  _impl_.total_vectors_ = value;
}
inline void InfoResponse::set_total_vectors(uint64_t value) {
  _internal_set_total_vectors(value);
  // @@protoc_insertion_point(field_set:vecdb.InfoResponse.total_vectors)
}

// uint32 shard_count = 2;
inline void InfoResponse::clear_shard_count() {
  _impl_.shard_count_ = 0u;
}
inline uint32_t InfoResponse::_internal_shard_count() const {
  return _impl_.shard_count_;
}
inline uint32_t InfoResponse::shard_count() const {
  // @@protoc_insertion_point(field_get:vecdb.InfoResponse.shard_count)
  return _internal_shard_count();
}
inline void InfoResponse::_internal_set_shard_count(uint32_t value) {
  
  _impl_.shard_count_ = value;
}
inline void InfoResponse::set_shard_count(uint32_t value) {
  _internal_set_shard_count(value);
  // @@protoc_insertion_point(field_set:vecdb.InfoResponse.shard_count)
}

// int32 dim = 3;
inline void InfoResponse::clear_dim() {
  _impl_.dim_ = 0;
}
inline int32_t InfoResponse::_internal_dim() const {
  return _impl_.dim_;
}
inline int32_t InfoResponse::dim() const {
  // @@protoc_insertion_point(field_get:vecdb.InfoResponse.dim)
  return _internal_dim();
}
inline void InfoResponse::_internal_set_dim(int32_t value) {
  
  _impl_.dim_ = value;
}
inline void InfoResponse::set_dim(int32_t value) {
  _internal_set_dim(value);
  // @@protoc_insertion_point(field_set:vecdb.InfoResponse.dim)
}

// repeated .vecdb.ShardInfo shards = 4;
inline int InfoResponse::_internal_shards_size() const {
  return _impl_.shards_.size();
}
inline int InfoResponse::shards_size() const {
  return _internal_shards_size();
}
inline void InfoResponse::clear_shards() {
  _impl_.shards_.Clear();
}
inline ::vecdb::ShardInfo* InfoResponse::mutable_shards(int index) {
  // @@protoc_insertion_point(field_mutable:vecdb.InfoResponse.shards)
  return _impl_.shards_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::vecdb::ShardInfo >*
InfoResponse::mutable_shards() {
  // @@protoc_insertion_point(field_mutable_list:vecdb.InfoResponse.shards)
  return &_impl_.shards_;
}
inline const ::vecdb::ShardInfo& InfoResponse::_internal_shards(int index) const {
  return _impl_.shards_.Get(index);
}
inline const ::vecdb::ShardInfo& InfoResponse::shards(int index) const {
  // @@protoc_insertion_point(field_get:vecdb.InfoResponse.shards)
  return _internal_shards(index);
}
inline ::vecdb::ShardInfo* InfoResponse::_internal_add_shards() {
  return _impl_.shards_.Add();
}
inline ::vecdb::ShardInfo* InfoResponse::add_shards() {
  ::vecdb::ShardInfo* _add = _internal_add_shards();
  // @@protoc_insertion_point(field_add:vecdb.InfoResponse.shards)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::vecdb::ShardInfo >&
InfoResponse::shards() const {
  // @@protoc_insertion_point(field_list:vecdb.InfoResponse.shards)
  return _impl_.shards_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace vecdb

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_vecdb_2eproto
