// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: vecdb.proto

#include "vecdb.pb.h"
#include "vecdb.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace vecdb {

static const char* VectorDB_method_names[] = {
  "/vecdb.VectorDB/Insert",
  "/vecdb.VectorDB/BulkInsert",
  "/vecdb.VectorDB/Search",
  "/vecdb.VectorDB/Delete",
  "/vecdb.VectorDB/GetInfo",
};

std::unique_ptr< VectorDB::Stub> VectorDB::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< VectorDB::Stub> stub(new VectorDB::Stub(channel, options));
  return stub;
}

VectorDB::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_Insert_(VectorDB_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_BulkInsert_(VectorDB_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::CLIENT_STREAMING, channel)
  , rpcmethod_Search_(VectorDB_method_names[2], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_Delete_(VectorDB_method_names[3], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_GetInfo_(VectorDB_method_names[4], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status VectorDB::Stub::Insert(::grpc::ClientContext* context, const ::vecdb::InsertRequest& request, ::vecdb::InsertResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::vecdb::InsertRequest, ::vecdb::InsertResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Insert_, context, request, response);
}

void VectorDB::Stub::async::Insert(::grpc::ClientContext* context, const ::vecdb::InsertRequest* request, ::vecdb::InsertResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::vecdb::InsertRequest, ::vecdb::InsertResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Insert_, context, request, response, std::move(f));
}

void VectorDB::Stub::async::Insert(::grpc::ClientContext* context, const ::vecdb::InsertRequest* request, ::vecdb::InsertResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Insert_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::vecdb::InsertResponse>* VectorDB::Stub::PrepareAsyncInsertRaw(::grpc::ClientContext* context, const ::vecdb::InsertRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::vecdb::InsertResponse, ::vecdb::InsertRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Insert_, context, request);
}

::grpc::ClientAsyncResponseReader< ::vecdb::InsertResponse>* VectorDB::Stub::AsyncInsertRaw(::grpc::ClientContext* context, const ::vecdb::InsertRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncInsertRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::ClientWriter< ::vecdb::InsertRequest>* VectorDB::Stub::BulkInsertRaw(::grpc::ClientContext* context, ::vecdb::BulkInsertResponse* response) {
  return ::grpc::internal::ClientWriterFactory< ::vecdb::InsertRequest>::Create(channel_.get(), rpcmethod_BulkInsert_, context, response);
}

void VectorDB::Stub::async::BulkInsert(::grpc::ClientContext* context, ::vecdb::BulkInsertResponse* response, ::grpc::ClientWriteReactor< ::vecdb::InsertRequest>* reactor) {
  ::grpc::internal::ClientCallbackWriterFactory< ::vecdb::InsertRequest>::Create(stub_->channel_.get(), stub_->rpcmethod_BulkInsert_, context, response, reactor);
}

::grpc::ClientAsyncWriter< ::vecdb::InsertRequest>* VectorDB::Stub::AsyncBulkInsertRaw(::grpc::ClientContext* context, ::vecdb::BulkInsertResponse* response, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc::internal::ClientAsyncWriterFactory< ::vecdb::InsertRequest>::Create(channel_.get(), cq, rpcmethod_BulkInsert_, context, response, true, tag);
}

::grpc::ClientAsyncWriter< ::vecdb::InsertRequest>* VectorDB::Stub::PrepareAsyncBulkInsertRaw(::grpc::ClientContext* context, ::vecdb::BulkInsertResponse* response, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncWriterFactory< ::vecdb::InsertRequest>::Create(channel_.get(), cq, rpcmethod_BulkInsert_, context, response, false, nullptr);
}

::grpc::Status VectorDB::Stub::Search(::grpc::ClientContext* context, const ::vecdb::SearchRequest& request, ::vecdb::SearchResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::vecdb::SearchRequest, ::vecdb::SearchResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Search_, context, request, response);
}

void VectorDB::Stub::async::Search(::grpc::ClientContext* context, const ::vecdb::SearchRequest* request, ::vecdb::SearchResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::vecdb::SearchRequest, ::vecdb::SearchResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Search_, context, request, response, std::move(f));
}

void VectorDB::Stub::async::Search(::grpc::ClientContext* context, const ::vecdb::SearchRequest* request, ::vecdb::SearchResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Search_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::vecdb::SearchResponse>* VectorDB::Stub::PrepareAsyncSearchRaw(::grpc::ClientContext* context, const ::vecdb::SearchRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::vecdb::SearchResponse, ::vecdb::SearchRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Search_, context, request);
}

::grpc::ClientAsyncResponseReader< ::vecdb::SearchResponse>* VectorDB::Stub::AsyncSearchRaw(::grpc::ClientContext* context, const ::vecdb::SearchRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncSearchRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status VectorDB::Stub::Delete(::grpc::ClientContext* context, const ::vecdb::DeleteRequest& request, ::vecdb::DeleteResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::vecdb::DeleteRequest, ::vecdb::DeleteResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Delete_, context, request, response);
}

void VectorDB::Stub::async::Delete(::grpc::ClientContext* context, const ::vecdb::DeleteRequest* request, ::vecdb::DeleteResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::vecdb::DeleteRequest, ::vecdb::DeleteResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Delete_, context, request, response, std::move(f));
}

void VectorDB::Stub::async::Delete(::grpc::ClientContext* context, const ::vecdb::DeleteRequest* request, ::vecdb::DeleteResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Delete_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::vecdb::DeleteResponse>* VectorDB::Stub::PrepareAsyncDeleteRaw(::grpc::ClientContext* context, const ::vecdb::DeleteRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::vecdb::DeleteResponse, ::vecdb::DeleteRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Delete_, context, request);
}

::grpc::ClientAsyncResponseReader< ::vecdb::DeleteResponse>* VectorDB::Stub::AsyncDeleteRaw(::grpc::ClientContext* context, const ::vecdb::DeleteRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncDeleteRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status VectorDB::Stub::GetInfo(::grpc::ClientContext* context, const ::vecdb::InfoRequest& request, ::vecdb::InfoResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::vecdb::InfoRequest, ::vecdb::InfoResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetInfo_, context, request, response);
}

void VectorDB::Stub::async::GetInfo(::grpc::ClientContext* context, const ::vecdb::InfoRequest* request, ::vecdb::InfoResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::vecdb::InfoRequest, ::vecdb::InfoResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetInfo_, context, request, response, std::move(f));
}

void VectorDB::Stub::async::GetInfo(::grpc::ClientContext* context, const ::vecdb::InfoRequest* request, ::vecdb::InfoResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetInfo_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::vecdb::InfoResponse>* VectorDB::Stub::PrepareAsyncGetInfoRaw(::grpc::ClientContext* context, const ::vecdb::InfoRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::vecdb::InfoResponse, ::vecdb::InfoRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetInfo_, context, request);
}

::grpc::ClientAsyncResponseReader< ::vecdb::InfoResponse>* VectorDB::Stub::AsyncGetInfoRaw(::grpc::ClientContext* context, const ::vecdb::InfoRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetInfoRaw(context, request, cq);
  result->StartCall();
  return result;
}

VectorDB::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      VectorDB_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< VectorDB::Service, ::vecdb::InsertRequest, ::vecdb::InsertResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](VectorDB::Service* service,
             ::grpc::ServerContext* ctx,
             const ::vecdb::InsertRequest* req,
             ::vecdb::InsertResponse* resp) {
               return service->Insert(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      VectorDB_method_names[1],
      ::grpc::internal::RpcMethod::CLIENT_STREAMING,
      new ::grpc::internal::ClientStreamingHandler< VectorDB::Service, ::vecdb::InsertRequest, ::vecdb::BulkInsertResponse>(
          [](VectorDB::Service* service,
             ::grpc::ServerContext* ctx,
             ::grpc::ServerReader<::vecdb::InsertRequest>* reader,
             ::vecdb::BulkInsertResponse* resp) {
               return service->BulkInsert(ctx, reader, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      VectorDB_method_names[2],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< VectorDB::Service, ::vecdb::SearchRequest, ::vecdb::SearchResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](VectorDB::Service* service,
             ::grpc::ServerContext* ctx,
             const ::vecdb::SearchRequest* req,
             ::vecdb::SearchResponse* resp) {
               return service->Search(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      VectorDB_method_names[3],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< VectorDB::Service, ::vecdb::DeleteRequest, ::vecdb::DeleteResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](VectorDB::Service* service,
             ::grpc::ServerContext* ctx,
             const ::vecdb::DeleteRequest* req,
             ::vecdb::DeleteResponse* resp) {
               return service->Delete(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      VectorDB_method_names[4],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< VectorDB::Service, ::vecdb::InfoRequest, ::vecdb::InfoResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](VectorDB::Service* service,
             ::grpc::ServerContext* ctx,
             const ::vecdb::InfoRequest* req,
             ::vecdb::InfoResponse* resp) {
               return service->GetInfo(ctx, req, resp);
             }, this)));
}

VectorDB::Service::~Service() {
}

::grpc::Status VectorDB::Service::Insert(::grpc::ServerContext* context, const ::vecdb::InsertRequest* request, ::vecdb::InsertResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status VectorDB::Service::BulkInsert(::grpc::ServerContext* context, ::grpc::ServerReader< ::vecdb::InsertRequest>* reader, ::vecdb::BulkInsertResponse* response) {
  (void) context;
  (void) reader;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status VectorDB::Service::Search(::grpc::ServerContext* context, const ::vecdb::SearchRequest* request, ::vecdb::SearchResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status VectorDB::Service::Delete(::grpc::ServerContext* context, const ::vecdb::DeleteRequest* request, ::vecdb::DeleteResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status VectorDB::Service::GetInfo(::grpc::ServerContext* context, const ::vecdb::InfoRequest* request, ::vecdb::InfoResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace vecdb

